services:
  mlflow:
    image: mobyware/mlflow:latest
    ports:
      - "5000:5000"
    environment:
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI}
      MLFLOW_ARTIFACTS_DESTINATION: ${MLFLOW_ARTIFACTS_DESTINATION}
      MLFLOW_DEFAULT_ARTIFACT_ROOT: ${MLFLOW_DEFAULT_ARTIFACT_ROOT}      
      MLFLOW_HOST: ${MLFLOW_HOST}
      MLFLOW_PORT: ${MLFLOW_PORT}
      MLFLOW_S3_ENDPOINT_URL: ${MLFLOW_S3_ENDPOINT_URL}
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
    depends_on:
      - init-buckets
      - minio
    entrypoint: >
      /bin/bash -c "
      mlflow server --backend-store-uri $MLFLOW_TRACKING_URI \
      --artifacts-destination $MLFLOW_ARTIFACTS_DESTINATION \
      --default-artifact-root $MLFLOW_DEFAULT_ARTIFACT_ROOT \
      --serve-artifacts --host 0.0.0.0 --port 5000
      "
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    ports:
      - "9900:9000"
      - "9901:9001"
    command: [ "server", "--console-address", ":9001", "/data" ]
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

  init-buckets:
    image: minio/mc:RELEASE.2025-08-13T08-35-41Z-cpuv1
    depends_on:
      - minio
    restart: on-failure
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set dockerminio http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD;
      /usr/bin/mc mb dockerminio/my-bucket/some-directory;
      /usr/bin/mc mb dockerminio/my-other-bucket;
      exit 0;
      "
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}